- hosts: dvalin.tf.fi
  become: yes
  tasks:
    - name: Install dependencies
      include_tasks: tasks/deps.yml
    
    - name: Build locally and rsync to server
      include_tasks: tasks/build.yml

    - name: Configure running backend
      include_tasks: tasks/backend.yml

    - name: Configure nginx
      include_tasks: tasks/nginx.yml
