- name: Specify git dir
  set_fact:
    git_dir: "{{ playbook_dir }}/lunch"
    url: lunch.dvalin.tf.fi

    #- name: Clone repo
    #  git:
    #    repo: https://github.com/Teknologforeningen/LUNCH.git
    #    dest: "{{ git_dir }}"
    #    force: yes
    #    version: HEAD

- name: Install apt packages
  package:
    name:
      - nodejs
      - npm
      - nginx
      - mongodb
    state: present

- name: Template nginx config
  template:
    src: lunch_nginx.conf.j2
    dest: /etc/nginx/sites-available/lunch
    mode: '0644'

- name: Link nginx config
  file:
    src: /etc/nginx/sites-available/lunch
    path: /etc/nginx/sites-enabled/lunch
    state: link

- name: Install npm packages
  delegate_to: localhost
  become: no
  npm:
    path: "{{ git_dir }}/lunch"
    state: present

- name: Run npm run build
  delegate_to: localhost
  become: no
  command:
    argv:
      - npm
      - run
      - build
    chdir: "{{ git_dir }}/lunch"

- name: Chown dir
  file:
    path: /srv/lunch-frontend
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
    recurse: yes

- name: Copy build dist
  ansible.posix.synchronize:
    src: "{{ git_dir }}/dist/"
    dest: /srv/lunch-frontend/


- name: Restart nginx
  service:
    name: nginx
    state: restarted
