- name: Specify git dir
  set_fact:
    git_dir: /srv/lunch
    url: lunch.dvalin.tf.fi

- name: Clone repo
  git:
    repo: https://github.com/Teknologforeningen/LUNCH.git
    dest: "{{ git_dir }}"
    force: yes
    version: HEAD

- name: Install apt packages
  package:
    name:
      - nodejs
      - npm
      - nginx
      - mongodb
    state: present

- name: Template nginx config
  template:
    src: lunch_nginx.conf.j2
    dest: /etc/nginx/sites-available/lunch
    mode: '0644'

- name: Link nginx config
  file:
    src: /etc/nginx/sites-available/lunch
    path: /etc/nginx/sites-enabled/lunch
    state: link

- name: Install npm packages
  npm:
    path: "{{ git_dir }}/lunch"
    state: present

- name: Run npm run build
  command:
    argv:
      - npm
      - run
      - build
    chdir: "{{ git_dir }}/lunch"

- name: Chown dir
  file:
    path: "/srv"
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
    recurse: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted
