- name: Clone repo
  git:
    repo: https://github.com/Teknologforeningen/LUNCH.git
    dest: /srv/lunch
    force: yes
    version: HEAD

- name: Install npm packages
  npm:
    path: /srv/lunch/lunch
    state: present

- name: Install apt packages
  package:
    name:
      - nodejs
      - npm
      - nginx
      - mongodb
    state: present
